import { 
    BarChart3, Newspaper, Layers, AlertOctagon, Calculator, 
    Globe, FileText, Building2, Users, FolderOpen, BookOpen, 
    Shield, Activity, Settings, MapPin 
  } from 'lucide-react';
  
  export const INITIAL_CLIENTS = [
    { id: 1, name: 'TechNova India Pvt Ltd', entity_type: 'WOS', sector: 'IT Services', parent_company: 'TechNova Inc.', parent_country: 'United States', tp_method: 'Safe Harbour', tp_margin: '15.5% Safe Harbour', risk_status: 'Green', annual_revenue_cr: 85, headcount: 320, compliance_score: 91, cbcr_applicable: false, master_file_applicable: false, sez_entity: false, gift_city: false, tasks: [{ id: 101, text: 'File Form 3CEFA (Safe Harbour election)', done: false, due: '2026-10-31', priority: 'High' }, { id: 102, text: 'Renew ICA with TechNova Inc.', done: false, due: '2026-06-30', priority: 'Medium' }], documents: [{ id: 1001, name: 'TP Study FY2024-25.pdf', category: 'TP Documentation', uploaded: '2025-10-20', expiry: '2026-10-31', status: 'Valid' }, { id: 1002, name: 'IT Services Agreement v3.docx', category: 'ICA', uploaded: '2024-04-01', expiry: '2026-03-31', status: 'Expiring Soon' }], notices: [], related_parties: [{ id: 1, name: 'TechNova Inc. (US Parent)', country: 'US', transaction_type: 'IT Services', amount_cr: 85, tp_method: 'Safe Harbour', arm_length: true }] },
    { id: 2, name: 'FinServe Global Services', entity_type: 'Branch', sector: 'BFSI', parent_company: 'FinServe Plc.', parent_country: 'United Kingdom', tp_method: 'Cost Plus', tp_margin: 'Cost Plus 10%', risk_status: 'Amber', annual_revenue_cr: 42, headcount: 180, compliance_score: 64, cbcr_applicable: true, master_file_applicable: true, sez_entity: false, gift_city: false, tasks: [{ id: 201, text: 'Review PE exposure — James Wilson (94 days)', done: false, due: '2026-05-15', priority: 'High' }, { id: 202, text: 'File CbCR notification (Form 3CEAC)', done: false, due: '2026-10-31', priority: 'High' }], documents: [{ id: 2001, name: 'Master File FY2024-25.pdf', category: 'TP Documentation', uploaded: '2025-11-01', expiry: '2026-10-31', status: 'Valid' }], notices: [{ id: 301, type: 'Income Tax', section: '142(1)', date_received: '2026-03-10', due_date: '2026-04-10', subject: 'Details of related party transactions FY2022-23', status: 'Responded' }], related_parties: [{ id: 2, name: 'FinServe Plc. (UK Parent)', country: 'UK', transaction_type: 'Management Services', amount_cr: 8.5, tp_method: 'Cost Plus', arm_length: true }] },
    { id: 3, name: 'HealthAI Innovation Labs', entity_type: 'LLP', sector: 'Healthcare Technology', parent_company: 'HealthAI Corp.', parent_country: 'Germany', tp_method: 'Pending', tp_margin: 'N/A (Pending)', risk_status: 'Red', annual_revenue_cr: 18, headcount: 95, compliance_score: 38, cbcr_applicable: false, master_file_applicable: false, sez_entity: false, gift_city: false, tasks: [{ id: 401, text: 'Draft TP Study — no documentation exists', done: false, due: '2026-05-10', priority: 'High' }, { id: 402, text: 'Respond to IT notice Section 142(1)', done: false, due: '2026-05-20', priority: 'High' }], documents: [], notices: [{ id: 601, type: 'Income Tax', section: '142(1)', date_received: '2026-04-20', due_date: '2026-05-20', subject: 'Furnish TP documentation for FY2023-24', status: 'Open' }], related_parties: [{ id: 4, name: 'HealthAI Corp. (Germany)', country: 'Germany', transaction_type: 'R&D Services', amount_cr: 18, tp_method: 'Pending', arm_length: null }] },
    { id: 4, name: 'Quantum Logistics GCC', entity_type: 'JV', sector: 'Supply Chain', parent_company: 'Quantum Global Ltd.', parent_country: 'Singapore', tp_method: 'CUP', tp_margin: 'CUP Method', risk_status: 'Green', annual_revenue_cr: 55, headcount: 210, compliance_score: 88, cbcr_applicable: false, master_file_applicable: false, sez_entity: false, gift_city: false, tasks: [{ id: 501, text: 'Renew Secretarial Audit engagement', done: false, due: '2026-09-30', priority: 'Low' }], documents: [{ id: 5001, name: 'Joint Venture Agreement 2019.pdf', category: 'Corporate', uploaded: '2019-07-05', expiry: '2029-06-30', status: 'Valid' }, { id: 5002, name: 'CUP Benchmarking Study FY2024.pdf', category: 'TP Documentation', uploaded: '2024-10-25', expiry: '2025-10-31', status: 'Expired' }], notices: [], related_parties: [{ id: 5, name: 'Quantum Global Ltd. (Singapore)', country: 'Singapore', transaction_type: 'Logistics Platform License', amount_cr: 5.5, tp_method: 'CUP', arm_length: true }] },
    { id: 5, name: 'GlobalRetail India WOS', entity_type: 'WOS', sector: 'Retail Technology', parent_company: 'GlobalRetail Corp.', parent_country: 'Netherlands', tp_method: 'TNMM', tp_margin: 'TNMM — 13.2%', risk_status: 'Amber', annual_revenue_cr: 38, headcount: 155, compliance_score: 72, cbcr_applicable: false, master_file_applicable: false, sez_entity: false, gift_city: false, tasks: [{ id: 701, text: 'Update TNMM benchmarking study (3-year refresh due)', done: false, due: '2026-09-30', priority: 'Medium' }], documents: [{ id: 7001, name: 'TNMM Study FY2023-24.pdf', category: 'TP Documentation', uploaded: '2024-10-28', expiry: '2025-10-31', status: 'Expired' }], notices: [], related_parties: [{ id: 6, name: 'GlobalRetail Corp. (Netherlands)', country: 'Netherlands', transaction_type: 'IT Services', amount_cr: 38, tp_method: 'TNMM', arm_length: true }] },
    { id: 6, name: 'NovaPharma R&D Centre', entity_type: 'WOS', sector: 'Pharmaceutical R&D', parent_company: 'NovaPharma AG', parent_country: 'Switzerland', tp_method: 'Cost Plus', tp_margin: 'Cost Plus 24% (Contract R&D)', risk_status: 'Red', annual_revenue_cr: 28, headcount: 130, compliance_score: 45, cbcr_applicable: false, master_file_applicable: false, sez_entity: true, gift_city: false, apa_status: 'Bilateral APA Filed', tasks: [{ id: 801, text: 'Respond to TPO questionnaire (AY 2023-24)', done: false, due: '2026-05-30', priority: 'High' }, { id: 802, text: 'Update APA pre-filing documentation', done: false, due: '2026-06-15', priority: 'High' }], documents: [{ id: 8001, name: 'APA Application FY2024.pdf', category: 'TP Documentation', uploaded: '2024-09-15', expiry: null, status: 'Valid' }], notices: [{ id: 901, type: 'Income Tax', section: 'TPO Reference', date_received: '2026-01-15', due_date: '2026-05-30', subject: "TP adjustment proposed — Contract R&D margin below arm's length", status: 'Open', amount_cr: 4.2 }], related_parties: [{ id: 7, name: 'NovaPharma AG (Switzerland)', country: 'Switzerland', transaction_type: 'Contract R&D Services', amount_cr: 28, tp_method: 'Cost Plus 24%', arm_length: true }] },
    { id: 7, name: 'MediaTech IFSC Unit', entity_type: 'WOS', sector: 'Financial Technology', parent_company: 'MediaTech Holdings Ltd.', parent_country: 'UAE', tp_method: 'TNMM', tp_margin: 'TNMM — 14.8%', risk_status: 'Green', annual_revenue_cr: 22, headcount: 75, compliance_score: 85, cbcr_applicable: false, master_file_applicable: false, sez_entity: false, gift_city: true, tasks: [{ id: 1001, text: 'File IFSCA annual return', done: false, due: '2026-06-30', priority: 'Medium' }], documents: [{ id: 10001, name: 'IFSCA Registration Certificate.pdf', category: 'Regulatory Approvals', uploaded: '2022-04-05', expiry: '2027-03-31', status: 'Valid' }], notices: [], related_parties: [{ id: 8, name: 'MediaTech Holdings Ltd. (UAE)', country: 'UAE', transaction_type: 'Financial Services', amount_cr: 22, tp_method: 'TNMM', arm_length: true }] },
    { id: 8, name: 'EngineerCo Branch Office', entity_type: 'Branch', sector: 'Engineering Services', parent_company: 'EngineerCo GmbH', parent_country: 'Germany', tp_method: 'Cost Plus', tp_margin: 'Cost Plus 12%', risk_status: 'Amber', annual_revenue_cr: 31, headcount: 140, compliance_score: 61, cbcr_applicable: false, master_file_applicable: false, sez_entity: false, gift_city: false, tasks: [{ id: 1101, text: 'Monitor Sarah Jenkins PE exposure (75 days)', done: false, due: '2026-06-01', priority: 'High' }, { id: 1102, text: 'File FLA Annual Return', done: false, due: '2026-07-15', priority: 'High' }], documents: [], notices: [], related_parties: [{ id: 9, name: 'EngineerCo GmbH (Germany)', country: 'Germany', transaction_type: 'Engineering Services', amount_cr: 31, tp_method: 'Cost Plus 12%', arm_length: true }] },
  ];
  
  export const INITIAL_EXPATS = [
    { id: 1, client_id: 2, client_name: 'FinServe Global Services', director_name: 'James Wilson', nationality: 'British', role: 'Managing Director', days_in_india: 94, dtaa_country: 'UK', pe_risk: 'TRIGGERED' },
    { id: 2, client_id: 8, client_name: 'EngineerCo Branch Office', director_name: 'Sarah Jenkins', nationality: 'German', role: 'Technical Director', days_in_india: 75, dtaa_country: 'Germany', pe_risk: 'Approaching' },
  ];
  
  export const INITIAL_TEAM = [
    { id: 1, email: 'partner@big4.com', name: 'Arjun Mehta', role: 'Admin', status: 'Active' },
    { id: 2, email: 'associate@big4.com', name: 'Priya Sharma', role: 'Editor', status: 'Active' },
    { id: 3, email: 'viewer@client.com', name: 'Rahul Gupta', role: 'Viewer', status: 'Pending' },
  ];
  
  export const PAGE_META = {
    overview: { title: 'Command Centre', sub: 'Firm-wide risk intelligence and advisory tools.' },
    regulatory: { title: 'Regulatory Intelligence Feed', sub: 'CBDT circulars, GST updates, RBI notifications and case law.' },
    clients: { title: 'Client Portfolios', sub: 'Master database of all active GCC entity structures.' },
    notices: { title: 'Notice Manager', sub: 'Track and respond to all income tax, GST and FEMA notices.' },
    tp: { title: 'Transfer Pricing Suite', sub: 'Method selection, benchmarking, APA and documentation engine.' },
    fema: { title: 'FEMA & RBI Compliance', sub: 'FDI register, FLA return, ECB tracker and repatriation modeller.' },
    gst: { title: 'GST Intelligence', sub: 'Export of services, ITC eligibility, RCM and SEZ rules.' },
    entity: { title: 'Entity Structuring Lab', sub: 'Compare entity types, model setup costs and incorporation journey.' },
    expat: { title: 'Expat & Shadow Payroll', sub: 'PE risk monitoring, residency calculator and shadow payroll.' },
    documents: { title: 'Document Vault', sub: 'Centralised storage with expiry tracking.' },
    ica: { title: 'ICA Builder', sub: 'Generate intercompany agreements from professional templates.' },
    reports: { title: 'Strategy Reports', sub: 'Build and export partner-ready advisory reports.' },
    compliance: { title: 'Compliance Calendar', sub: 'All 40+ annual filings tracked across all applicable laws.' },
    audit: { title: 'Audit Trail', sub: 'Immutable log of all firm-wide data access and modifications.' },
    settings: { title: 'Firm Settings', sub: 'Manage firm profile, team access, billing and security.' },
  };